### ISSUE TITLE
Support for TypeDoc 0.27

### ISSUE THREAD

**Issue by jan-molak** [krisztianb/typedoc-plugin-replace-text#12]
Hi @krisztianb! TypeDoc 0.27 is now available, and it would be great if `typedoc-plugin-replace-text` could support it. 

Thanks in advance and thank you for all your work on this plugin!

**Comment by krisztianb** [comment]
Hi Jan. I'm glad that the plugin is helpful for you. I should have time during the following week to update the plugin to support TypeDoc 0.27.

**Comment by krisztianb** [comment]
I published a new version **4.1.0** on NPM which works with TypeDoc 0.27.x 🎉 

My tests are passing. Please report back if something is not working as expected. Thank you.
