### ISSUE TITLE
Could you release a version which is compatible with typedoc 0.24.x?

### ISSUE THREAD

**Issue by kozi** [krisztianb/typedoc-plugin-replace-text#2]
#### Could you release a version which is compatible with typedoc 0.24.x?

https://github.com/krisztianb/typedoc-plugin-replace-text/blob/053205fc24b0bc88a5717b9ee35b6632d0b274d0/package.json#L27

**Comment by krisztianb** [comment]
Sure. Did you run into any errors with the plugin after upgrading TypeDoc to 0.24 or is it only about the peer dependency warning?

**Comment by krisztianb** [comment]
I tested the plugin with TypeDoc version 0.24.2 and found it to be still fully functional. So I only updated the peer dependency of the package to get rid of the NPM warning when installing it.

This is now released as version **2.2.0**

If you run into problems let me know.

**Comment by kozi** [comment]
Works for me! 👍

**Comment by kozi** [comment]
A little hint for the documentation: Plugins can also be specified/activated in the config file

```javascript
/** @type import("typedoc").TypeDocOptions */
module.exports = {
    entryPoints: [
        "./src/index.ts"
    ],
    plugin: [
        "typedoc-plugin-replace-text"
    ],
    media: "media",
    out: "public",
    //...
```
