### ISSUE TITLE
Could you release a version which is compatible with typedoc 0.25.x?

### ISSUE THREAD

**Issue by kozi** [krisztianb/typedoc-plugin-replace-text#7]
#### Could you release a version which is compatible with typedoc 0.25.x?

https://github.com/krisztianb/typedoc-plugin-replace-text/blob/aafca6937b564778602440429a2fd0cef23519c7/package.json#L29

Maybe: `"typedoc": "0.24.x | 0.25.x"`

**Comment by krisztianb** [comment]
Sure. Although I will have to first check if the plugin is still working correctly with the latest version.

**Comment by krisztianb** [comment]
Luckily the plugin is still working properly.

Version support for TypeDoc 0.25.x has been added in the latest release **3.2.0** 🎉
